name: aCommands
version: ${project.version}
main: com.ionly.acommands.aCommands
commands:
  amenubruh:
    description: bruh to whole server.
    usage: /<command>
  autils-info:
    description: display the version of aUtils that cureently running on.
    usage: /<command>
  bemonke:
    description: transform you to be monke!!.
    usage: /<command>